services:
  zabbix-db:
    image: postgres:15-alpine
    container_name: zabbix-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data
    networks:
      - obs-network

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    restart: always
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    depends_on:
      - zabbix-db
    networks:
      - obs-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    depends_on:
      - zabbix-server
    networks:
      - obs-network

  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app 4.4.3,oci-metrics-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-app,oci-datasource,oracle-oci-datasource,oci-metrics-datasource
      # AWS
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      # Azure
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      # GCP
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_CLIENT_EMAIL=${GCP_CLIENT_EMAIL}
      - GCP_PRIVATE_KEY=${GCP_PRIVATE_KEY}
      # OCI
      - OCI_TENANCY_OCID=${OCI_TENANCY_OCID}
      - OCI_USER_OCID=${OCI_USER_OCID}
      - OCI_FINGERPRINT=${OCI_FINGERPRINT}
      - OCI_REGION=${OCI_REGION}
      - OCI_PRIVATE_KEY=${OCI_PRIVATE_KEY}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./warleirf@hotmail.com-2026-08-15T20_20_03.352Z.pem:/etc/grafana/warleirf@hotmail.com-2026-08-15T20_20_03.352Z.pem:ro
      - ./grafana/site-portifolio-429900-1bef20715226.json:/etc/grafana/site-portifolio-429900-1bef20715226.json:ro
    depends_on:
      - zabbix-web
    networks:
      - obs-network

networks:
  obs-network:
    driver: bridge

volumes:
  zabbix-db-data:
  grafana-data: