apiVersion: 1

datasources:
  - name: AWS CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: keys
      defaultRegion: ${AWS_DEFAULT_REGION}
    secureJsonData:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

  - name: Azure Monitor
    type: grafana-azure-monitor-datasource
    access: proxy
    jsonData:
      clientId: ${AZURE_CLIENT_ID}
      tenantId: ${AZURE_TENANT_ID}
      subscriptionId: ${AZURE_SUBSCRIPTION_ID}
    secureJsonData:
      clientSecret: ${AZURE_CLIENT_SECRET}

  - name: GCP Cloud Monitoring
    type: stackdriver
    access: proxy
    jsonData:
      authenticationType: jwt
      clientEmail: ${GCP_CLIENT_EMAIL}
      defaultProject: ${GCP_PROJECT_ID}
      tokenUri: https://oauth2.googleapis.com/token
    secureJsonData:
      privateKey: ${GCP_PRIVATE_KEY}

  - name: Oracle Cloud Infrastructure Metrics
    type: oracle-oci-datasource
    access: proxy
    jsonData:
      authType: API Key
      tenancyMode: single
      tenancy: ${OCI_TENANCY_OCID}
      user: ${OCI_USER_OCID}
      fingerprint: ${OCI_FINGERPRINT}
      region: ${OCI_REGION}
    secureJsonData:
      privateKey: ${OCI_PRIVATE_KEY}

  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://zabbix-web:8080/api_jsonrpc.php
    jsonData:
      username: Admin
      password: zabbix